const mongoose = require("mongoose");

const breedSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      required: true,
      unique: true,
      trim: true,
    },

    // Case/whitespace-insensitive form of `name`, kept in a unique index.
    //
    // The plain `name` unique index above is case-SENSITIVE, so without
    // this two records — "Golden Retriever" and "golden retriever" — could
    // both be created and the breed page would show the same animal twice.
    // Every write path (admin create, pet-create fallback, seed, AI
    // enrichment) goes through this hook, so no caller can bypass it.
    normalizedName: {
      type: String,
      index: { unique: true, sparse: true },
    },

    // Other names the same breed is known by, so a second record for the
    // same animal can be found and merged instead of duplicated. Used by
    // the AI breed pipeline when it normalizes an ImageNet label.
    aliases: [
      {
        type: String,
        trim: true,
      },
    ],

    // Case/whitespace-insensitive form of each alias, derived by the
    // hook below for the same reason `normalizedName` is: "Lab" and
    // "lab" are the same name, and a lookup has to find either one
    // without scanning every record in JS.
    normalizedAliases: [
      {
        type: String,
      },
    ],

    species: {
      type: String,
      required: true,
      enum: ["dog", "cat", "bird", "rabbit", "fish", "other"],
      lowercase: true,
      trim: true,
    },

    origin: {
      type: String,
      trim: true,
      default: "",
    },

    lifespan: {
      type: String,
      default: "",
    },

    weightRange: {
      type: String,
      default: "",
    },

    heightRange: {
      type: String,
      default: "",
    },

    temperament: [
      {
        type: String,
        trim: true,
      },
    ],

    exerciseRequirements: {
      type: String,
      default: "",
    },

    groomingGuide: {
      type: String,
      default: "",
    },

    commonDiseases: [
      {
        type: String,
        trim: true,
      },
    ],

    suitableEnvironment: {
      type: String,
      default: "",
    },

    // Short distinguishing traits that do not belong to temperament
    // (a colour pattern, a coat type, a body feature).
    characteristics: [
      {
        type: String,
        trim: true,
      },
    ],

    nutritionNotes: {
      type: String,
      default: "",
    },

    description: {
      type: String,
      default: "",
    },

    images: [
      {
        type: String,
      },
    ],

    popularity: {
      type: Number,
      default: 0,
      min: 0,
    },

    // Where this record's content came from. `curated` = seeded or written
    // by an admin; `ai` = generated by the breed-enrichment step. The Breed
    // page reads this so an AI-written record is never presented as
    // human-verified.
    source: {
      type: String,
      enum: ["curated", "ai"],
      default: "curated",
      lowercase: true,
      trim: true,
    },

    // The ImageNet class slug that produced this record, when it was
    // created by breed identification. Empty for every other breed.
    imagenetLabel: {
      type: String,
      default: "",
      trim: true,
    },

    // Whether a human has checked the content. Anything produced by the AI
    // starts `unverified` and is only promoted by an admin edit.
    verificationStatus: {
      type: String,
      enum: ["verified", "unverified"],
      default: "unverified",
      lowercase: true,
      trim: true,
    },

    isActive: {
      type: Boolean,
      default: true,
    },
  },
  {
    timestamps: true,
  }
);

// Single source of truth for the comparison key, so the hook below and
// every lookup in the breed-AI service agree byte for byte.
function breedKey(value) {
  return String(value == null ? "" : value)
    .normalize("NFKD")
    .replace(/[̀-ͯ]/g, "") // strip combining marks (é -> e)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

breedSchema.statics.keyOf = function (value) {
  return breedKey(value);
};

// Derive `normalizedName` from `name` on every save. Doing it here rather
// than at each call site is the point: the uniqueness rule then holds for
// every writer, including ones that did not know the rule existed.
breedSchema.pre("validate", function (next) {
  if (this.name !== undefined && this.name !== null) {
    this.normalizedName = breedKey(this.name) || undefined;
  }
  if (Array.isArray(this.aliases)) {
    // Keep only distinct keys, and drop the breed's own name so an
    // alias can never shadow a different record's name.
    this.normalizedAliases = [
      ...new Set(
        this.aliases
          .map((alias) => breedKey(alias))
          .filter((key) => key && key !== this.normalizedName)
      ),
    ];
  }
  next();
});

module.exports = mongoose.model("Breed", breedSchema);